# Generated by Django 5.1.3 on 2024-12-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="college",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
